'use strict';

const { AppError } = require('../../utils/errors');

const OPERATION_STATE = Object.freeze({
  REQUESTED: 'REQUESTED',
  VALIDATING: 'VALIDATING',
  QUOTED: 'QUOTED',
  AUTHORIZED: 'AUTHORIZED',
  RESERVED: 'RESERVED',
  PROCESSING: 'PROCESSING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  UNKNOWN: 'UNKNOWN',
  RECONCILING: 'RECONCILING',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
  REFUNDED: 'REFUNDED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
  REQUIRES_ACTION: 'REQUIRES_ACTION'
});

const TERMINAL_STATES = Object.freeze(new Set([
  OPERATION_STATE.SUCCEEDED,
  OPERATION_STATE.FAILED,
  OPERATION_STATE.CANCELLED,
  OPERATION_STATE.EXPIRED,
  OPERATION_STATE.REFUNDED
]));

const TRANSITIONS = Object.freeze({
  [OPERATION_STATE.REQUESTED]: [OPERATION_STATE.VALIDATING, OPERATION_STATE.CANCELLED, OPERATION_STATE.EXPIRED],
  [OPERATION_STATE.VALIDATING]: [OPERATION_STATE.QUOTED, OPERATION_STATE.REQUIRES_ACTION, OPERATION_STATE.FAILED, OPERATION_STATE.CANCELLED],
  [OPERATION_STATE.QUOTED]: [OPERATION_STATE.AUTHORIZED, OPERATION_STATE.REQUIRES_ACTION, OPERATION_STATE.EXPIRED, OPERATION_STATE.CANCELLED],
  [OPERATION_STATE.AUTHORIZED]: [OPERATION_STATE.RESERVED, OPERATION_STATE.REQUIRES_ACTION, OPERATION_STATE.FAILED, OPERATION_STATE.CANCELLED],
  [OPERATION_STATE.RESERVED]: [OPERATION_STATE.PROCESSING, OPERATION_STATE.CANCELLED, OPERATION_STATE.EXPIRED],
  [OPERATION_STATE.PROCESSING]: [OPERATION_STATE.SUCCEEDED, OPERATION_STATE.FAILED, OPERATION_STATE.UNKNOWN, OPERATION_STATE.REQUIRES_ACTION],
  [OPERATION_STATE.UNKNOWN]: [OPERATION_STATE.RECONCILING],
  [OPERATION_STATE.RECONCILING]: [OPERATION_STATE.SUCCEEDED, OPERATION_STATE.FAILED, OPERATION_STATE.REQUIRES_ACTION],
  [OPERATION_STATE.REQUIRES_ACTION]: [OPERATION_STATE.AUTHORIZED, OPERATION_STATE.CANCELLED, OPERATION_STATE.FAILED],
  [OPERATION_STATE.SUCCEEDED]: [OPERATION_STATE.REFUNDED, OPERATION_STATE.PARTIALLY_REFUNDED],
  [OPERATION_STATE.PARTIALLY_REFUNDED]: [OPERATION_STATE.REFUNDED],
  [OPERATION_STATE.FAILED]: [OPERATION_STATE.REQUIRES_ACTION],
  [OPERATION_STATE.CANCELLED]: [],
  [OPERATION_STATE.EXPIRED]: [],
  [OPERATION_STATE.REFUNDED]: []
});

function assertKnownState(state) {
  if (!Object.prototype.hasOwnProperty.call(TRANSITIONS, state)) {
    throw new AppError(409, 'FINANCIAL_OPERATION_STATE_UNKNOWN', `Unknown financial operation state: ${state}.`, { state });
  }
}

function canTransition(from, to) {
  assertKnownState(from);
  assertKnownState(to);
  return TRANSITIONS[from].includes(to);
}

function assertTransition(from, to) {
  if (!canTransition(from, to)) {
    throw new AppError(409, 'FINANCIAL_OPERATION_STATE_TRANSITION_INVALID',
      `Cannot transition financial operation from ${from} to ${to}.`, {
        from,
        to,
        allowed: TRANSITIONS[from]
      });
  }
}

function transitionState({ state, nextState, actorId = null, reason = null, at = new Date().toISOString() }) {
  assertTransition(state, nextState);
  return Object.freeze({
    previousState: state,
    state: nextState,
    actorId,
    reason,
    at,
    terminal: TERMINAL_STATES.has(nextState),
    requiresReconciliation: nextState === OPERATION_STATE.UNKNOWN || nextState === OPERATION_STATE.RECONCILING
  });
}

module.exports = {
  OPERATION_STATE,
  TERMINAL_STATES,
  TRANSITIONS,
  assertKnownState,
  assertTransition,
  canTransition,
  transitionState
};
