'use strict';

const PAYMENT_STATES = Object.freeze({
  CREATED: 'CREATED', PROCESSING: 'PROCESSING', AUTHORIZED: 'AUTHORIZED',
  SUCCEEDED: 'SUCCEEDED', FAILED: 'FAILED', CANCELLED: 'CANCELLED',
  UNKNOWN: 'UNKNOWN', RECONCILING: 'RECONCILING', EXPIRED: 'EXPIRED'
});

const PAYMENT_TRANSITIONS = Object.freeze({
  [PAYMENT_STATES.CREATED]: [PAYMENT_STATES.PROCESSING, PAYMENT_STATES.CANCELLED, PAYMENT_STATES.FAILED, PAYMENT_STATES.EXPIRED],
  [PAYMENT_STATES.PROCESSING]: [PAYMENT_STATES.AUTHORIZED, PAYMENT_STATES.SUCCEEDED, PAYMENT_STATES.FAILED, PAYMENT_STATES.CANCELLED, PAYMENT_STATES.UNKNOWN],
  [PAYMENT_STATES.AUTHORIZED]: [PAYMENT_STATES.SUCCEEDED, PAYMENT_STATES.FAILED, PAYMENT_STATES.CANCELLED, PAYMENT_STATES.UNKNOWN],
  [PAYMENT_STATES.SUCCEEDED]: [],
  [PAYMENT_STATES.FAILED]: [PAYMENT_STATES.RECONCILING, PAYMENT_STATES.SUCCEEDED],
  [PAYMENT_STATES.CANCELLED]: [PAYMENT_STATES.RECONCILING],
  [PAYMENT_STATES.UNKNOWN]: [PAYMENT_STATES.RECONCILING, PAYMENT_STATES.SUCCEEDED, PAYMENT_STATES.FAILED],
  [PAYMENT_STATES.RECONCILING]: [PAYMENT_STATES.SUCCEEDED, PAYMENT_STATES.FAILED, PAYMENT_STATES.CANCELLED, PAYMENT_STATES.PROCESSING],
  [PAYMENT_STATES.EXPIRED]: []
});

const PAYOUT_STATES = Object.freeze({
  REQUESTED: 'REQUESTED', RISK_CHECK: 'RISK_CHECK',
  AUTO_APPROVED: 'AUTO_APPROVED', MANUAL_REVIEW: 'MANUAL_REVIEW',
  // Legacy alias kept for backward compatibility with existing flows that still
  // persist PENDING_APPROVAL. New code should use MANUAL_REVIEW.
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED', REJECTED: 'REJECTED', RESERVED: 'RESERVED',
  PROCESSING: 'PROCESSING', SUBMITTED: 'SUBMITTED', SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED', UNKNOWN: 'UNKNOWN', RECONCILING: 'RECONCILING', CANCELLED: 'CANCELLED'
});

const PAYOUT_TRANSITIONS = Object.freeze({
  [PAYOUT_STATES.REQUESTED]: [PAYOUT_STATES.RISK_CHECK, PAYOUT_STATES.REJECTED, PAYOUT_STATES.CANCELLED],
  [PAYOUT_STATES.RISK_CHECK]: [
    PAYOUT_STATES.AUTO_APPROVED,
    PAYOUT_STATES.MANUAL_REVIEW,
    PAYOUT_STATES.PENDING_APPROVAL,
    PAYOUT_STATES.APPROVED,
    PAYOUT_STATES.REJECTED,
    PAYOUT_STATES.CANCELLED
  ],
  // AUTO_APPROVED: low-risk payout that passed policy and needs no human review.
  [PAYOUT_STATES.AUTO_APPROVED]: [PAYOUT_STATES.APPROVED, PAYOUT_STATES.RESERVED, PAYOUT_STATES.PROCESSING, PAYOUT_STATES.CANCELLED],
  // MANUAL_REVIEW: high-risk or policy-flagged payout awaiting an operator.
  [PAYOUT_STATES.MANUAL_REVIEW]: [PAYOUT_STATES.APPROVED, PAYOUT_STATES.REJECTED, PAYOUT_STATES.CANCELLED, PAYOUT_STATES.RESERVED],
  [PAYOUT_STATES.PENDING_APPROVAL]: [PAYOUT_STATES.APPROVED, PAYOUT_STATES.REJECTED, PAYOUT_STATES.CANCELLED],
  [PAYOUT_STATES.APPROVED]: [PAYOUT_STATES.RESERVED, PAYOUT_STATES.PROCESSING, PAYOUT_STATES.CANCELLED],
  [PAYOUT_STATES.REJECTED]: [],
  [PAYOUT_STATES.RESERVED]: [PAYOUT_STATES.PROCESSING, PAYOUT_STATES.CANCELLED],
  [PAYOUT_STATES.PROCESSING]: [PAYOUT_STATES.SUBMITTED, PAYOUT_STATES.SUCCEEDED, PAYOUT_STATES.FAILED, PAYOUT_STATES.UNKNOWN],
  [PAYOUT_STATES.SUBMITTED]: [PAYOUT_STATES.SUCCEEDED, PAYOUT_STATES.FAILED, PAYOUT_STATES.UNKNOWN],
  [PAYOUT_STATES.SUCCEEDED]: [],
  [PAYOUT_STATES.FAILED]: [PAYOUT_STATES.RECONCILING, PAYOUT_STATES.SUCCEEDED],
  [PAYOUT_STATES.UNKNOWN]: [PAYOUT_STATES.RECONCILING, PAYOUT_STATES.SUCCEEDED, PAYOUT_STATES.FAILED],
  [PAYOUT_STATES.RECONCILING]: [PAYOUT_STATES.SUCCEEDED, PAYOUT_STATES.FAILED, PAYOUT_STATES.CANCELLED, PAYOUT_STATES.PROCESSING],
  [PAYOUT_STATES.CANCELLED]: [PAYOUT_STATES.RECONCILING]
});

const TERMINAL_PAYMENT = [PAYMENT_STATES.SUCCEEDED, PAYMENT_STATES.EXPIRED];
const TERMINAL_PAYOUT = [PAYOUT_STATES.SUCCEEDED, PAYOUT_STATES.REJECTED];

function isValidPaymentTransition(from, to) {
  const allowed = PAYMENT_TRANSITIONS[from];
  return allowed ? allowed.includes(to) : false;
}

function isValidPayoutTransition(from, to) {
  const allowed = PAYOUT_TRANSITIONS[from];
  return allowed ? allowed.includes(to) : false;
}

function assertPaymentTransition(from, to) {
  if (!isValidPaymentTransition(from, to)) {
    const err = new Error('Invalid payment transition: ' + from + ' -> ' + to);
    err.code = 'INVALID_STATE_TRANSITION';
    err.previousState = from;
    err.requestedState = to;
    throw err;
  }
}

function assertPayoutTransition(from, to) {
  if (!isValidPayoutTransition(from, to)) {
    const err = new Error('Invalid payout transition: ' + from + ' -> ' + to);
    err.code = 'INVALID_STATE_TRANSITION';
    err.previousState = from;
    err.requestedState = to;
    throw err;
  }
}

module.exports = {
  PAYMENT_STATES, PAYMENT_TRANSITIONS, TERMINAL_PAYMENT,
  PAYOUT_STATES, PAYOUT_TRANSITIONS, TERMINAL_PAYOUT,
  isValidPaymentTransition, isValidPayoutTransition,
  assertPaymentTransition, assertPayoutTransition
};
