const INVOICE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  SCHEDULED: 'SCHEDULED',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
  UPDATED: 'UPDATED',
  FAILED: 'FAILED'
});

const PAYOUT_STATUS = Object.freeze({
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  QUEUED: 'QUEUED',
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  PENDING: 'PENDING',
  DENIED: 'DENIED',
  REJECTED: 'REJECTED',
  ON_HOLD: 'ON_HOLD'
});

const RISK_DECISION = Object.freeze({
  APPROVED: 'APPROVED',
  REVIEW: 'REVIEW',
  BLOCKED: 'BLOCKED'
});

const RISK_DOMAIN = Object.freeze({
  PAYMENT: 'PAYMENT_RISK',
  ACCOUNT: 'ACCOUNT_RISK',
  SERVICE: 'SERVICE_RISK',
  VELOCITY: 'VELOCITY_RISK',
  ADMIN: 'ADMIN_RISK'
});

const ACCOUNT_RISK_STATE = Object.freeze({
  NORMAL: 'NORMAL',
  WATCH: 'WATCH',
  REVIEW: 'REVIEW',
  RESTRICTED: 'RESTRICTED',
  SUSPENDED: 'SUSPENDED'
});

const RISK_LEVEL = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
});

const RISK_ENGINE_DECISION = Object.freeze({
  ALLOW: 'ALLOW',
  ALLOW_WITH_MONITORING: 'ALLOW_WITH_MONITORING',
  REQUIRE_REVIEW: 'REQUIRE_REVIEW',
  REQUIRE_VERIFICATION: 'REQUIRE_VERIFICATION',
  TEMPORARILY_RESTRICT: 'TEMPORARILY_RESTRICT',
  BLOCK: 'BLOCK'
});

const RISK_CASE_STATUS = Object.freeze({
  OPEN: 'OPEN',
  INVESTIGATING: 'INVESTIGATING',
  WAITING_FOR_INFORMATION: 'WAITING_FOR_INFORMATION',
  RESOLVED: 'RESOLVED',
  FALSE_POSITIVE: 'FALSE_POSITIVE',
  ESCALATED: 'ESCALATED'
});

const ACCOUNT_RESTRICTION_CAPABILITY = Object.freeze({
  FUNDING_RESTRICTED: 'FUNDING_RESTRICTED',
  REFUNDS_RESTRICTED: 'REFUNDS_RESTRICTED',
  HIGH_VALUE_SERVICES_RESTRICTED: 'HIGH_VALUE_SERVICES_RESTRICTED',
  API_ACCESS_RESTRICTED: 'API_ACCESS_RESTRICTED',
  ACCOUNT_CHANGES_RESTRICTED: 'ACCOUNT_CHANGES_RESTRICTED'
});

const LEDGER_ENTRY_TYPE = Object.freeze({
  INVOICE_PENDING_CREDIT: 'INVOICE_PENDING_CREDIT',
  FUNDS_RELEASE: 'FUNDS_RELEASE',
  PAYOUT_RESERVE: 'PAYOUT_RESERVE',
  PAYOUT_SETTLED: 'PAYOUT_SETTLED',
  PAYOUT_RELEASE_REFUND: 'PAYOUT_RELEASE_REFUND',
  INVOICE_REFUND_ADJUSTMENT: 'INVOICE_REFUND_ADJUSTMENT',
  MANUAL_ADJUSTMENT: 'MANUAL_ADJUSTMENT'
});

const BALANCE_BUCKET = Object.freeze({
  PENDING: 'PENDING',
  AVAILABLE: 'AVAILABLE',
  FROZEN: 'FROZEN',
  PAID_OUT: 'PAID_OUT'
});

const AUDIT_ACTOR_TYPE = Object.freeze({
  SYSTEM: 'SYSTEM',
  USER: 'USER',
  ADMIN: 'ADMIN',
  WEBHOOK: 'WEBHOOK'
});

const USER_STATUS = Object.freeze({
  ACTIVE: 'active',
  SUSPENDED: 'suspended',
  RESTRICTED: 'restricted',
  DELETED: 'deleted'
});

const WEBHOOK_PROCESSING_STATUS = Object.freeze({
  RECEIVED: 'RECEIVED',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  PROCESSED: 'PROCESSED',
  FAILED: 'FAILED',
  IGNORED: 'IGNORED'
});

const RISK_FLAG_SEVERITY = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
});

const RISK_FLAG_STATUS = Object.freeze({
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED',
  DISMISSED: 'DISMISSED'
});

const RECIPIENT_TYPE = Object.freeze({
  EMAIL: 'EMAIL',
  PHONE: 'PHONE',
  PAYPAL_ID: 'PAYPAL_ID'
});

const RECEIPT_TYPE = Object.freeze({
  BANK: 'bank',
  EMAIL: 'email'
});

const RECEIPT_STATUS = Object.freeze({
  GENERATED: 'GENERATED',
  EMAILED: 'EMAILED'
});

const POINT_TRANSACTION_TYPE = Object.freeze({
  LEDGER_OPENING_BALANCE: 'LEDGER_OPENING_BALANCE',
  SIGNUP_BONUS: 'SIGNUP_BONUS',
  REFERRAL_BONUS: 'REFERRAL_BONUS',
  RECEIPT_SPEND: 'RECEIPT_SPEND',
  EMAIL_SPEND: 'EMAIL_SPEND',
  TOP_UP_PURCHASE: 'TOP_UP_PURCHASE',
  PURCHASE_CREDIT: 'PURCHASE_CREDIT',
  ADMIN_ADJUSTMENT: 'ADMIN_ADJUSTMENT',
  POINT_PROJECTION_RECONCILIATION: 'POINT_PROJECTION_RECONCILIATION',
  POINT_RESERVATION_HOLD: 'POINT_RESERVATION_HOLD',
  POINT_RESERVATION_COMMIT: 'POINT_RESERVATION_COMMIT',
  POINT_RESERVATION_RELEASE: 'POINT_RESERVATION_RELEASE'
});

const POINT_RESERVATION_STATUS = Object.freeze({
  RESERVED: 'RESERVED',
  COMMITTED: 'COMMITTED',
  RELEASED: 'RELEASED',
  EXPIRED: 'EXPIRED'
});

const ORDER_STATUS = Object.freeze({
  DRAFT: 'draft',
  VALIDATING: 'validating',
  PREFLIGHT: 'preflight',
  POINTS_RESERVED: 'points_reserved',
  QUEUED: 'queued',
  PROCESSING: 'processing',
  COMPLETED: 'completed',
  VALIDATION_FAILED: 'validation_failed',
  INSUFFICIENT_POINTS: 'insufficient_points',
  MANUAL_REVIEW: 'manual_review',
  FAILED: 'failed',
  CANCELLED: 'cancelled',
  EXPIRED: 'expired',
  REFUNDED: 'refunded'
});

const ORDER_QUEUE_STATUS = Object.freeze({
  PENDING: 'pending',
  DISPATCH_PENDING: 'dispatch_pending',
  DISPATCHED: 'dispatched',
  PROCESSING: 'processing',
  UNAVAILABLE: 'unavailable'
});

const ORDER_ATTEMPT_STATUS = Object.freeze({
  PROCESSING: 'processing',
  SUCCEEDED: 'succeeded',
  FAILED: 'failed',
  STALE: 'stale'
});

const DEAD_LETTER_STATUS = Object.freeze({
  OPEN: 'open',
  RECOVERY_PENDING: 'recovery_pending',
  RECOVERED: 'recovered',
  RECOVERY_FAILED: 'recovery_failed'
});

const WORKER_FAILURE_CLASSIFICATION = Object.freeze({
  RETRYABLE: 'retryable',
  TERMINAL: 'terminal'
});

const TOP_UP_ORDER_STATUS = Object.freeze({
  PENDING: 'pending',
  AWAITING_CONFIRMATION: 'awaiting_confirmation',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled'
});

const POINTS_FUNDING_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PAYMENT_INSTRUCTIONS: 'PAYMENT_INSTRUCTIONS',
  PAYMENT_REPORTED: 'PAYMENT_REPORTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  POINTS_CREDITED: 'POINTS_CREDITED',
  REJECTED: 'REJECTED',
  NEEDS_MORE_INFORMATION: 'NEEDS_MORE_INFORMATION',
  CANCELLED: 'CANCELLED',
  MANUAL_REVIEW: 'MANUAL_REVIEW'
});

const EMAIL_DISPATCH_STATUS = Object.freeze({
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
  LOCAL_ONLY: 'LOCAL_ONLY'
});

module.exports = {
  INVOICE_STATUS,
  PAYOUT_STATUS,
  RISK_DECISION,
  RISK_DOMAIN,
  ACCOUNT_RISK_STATE,
  RISK_LEVEL,
  RISK_ENGINE_DECISION,
  RISK_CASE_STATUS,
  ACCOUNT_RESTRICTION_CAPABILITY,
  LEDGER_ENTRY_TYPE,
  BALANCE_BUCKET,
  AUDIT_ACTOR_TYPE,
  USER_STATUS,
  WEBHOOK_PROCESSING_STATUS,
  RISK_FLAG_SEVERITY,
  RISK_FLAG_STATUS,
  RECIPIENT_TYPE,
  RECEIPT_TYPE,
  RECEIPT_STATUS,
  POINT_TRANSACTION_TYPE,
  POINT_RESERVATION_STATUS,
  ORDER_STATUS,
  ORDER_QUEUE_STATUS,
  ORDER_ATTEMPT_STATUS,
  DEAD_LETTER_STATUS,
  WORKER_FAILURE_CLASSIFICATION,
  TOP_UP_ORDER_STATUS,
  POINTS_FUNDING_STATUS,
  EMAIL_DISPATCH_STATUS
};
