const path = require('node:path');
const { mkdirSync } = require('node:fs');
const dotenv = require('dotenv');
const { z } = require('zod');

const { deriveEnvironmentConfig, validateProductionConfig } = require('./core/config/environment');

dotenv.config();

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  PORT: z.coerce.number().int().positive().default(3000),
  APP_BASE_URL: z.string().url().default('http://localhost:3001'),
  FRONTEND_URL: z.string().url().default('http://localhost:3000'),
  SQLITE_DATABASE_PATH: z.string().min(1).default('./data/transferly.sqlite'),
  REDIS_URL: z.string().min(1),
  INLINE_QUEUE_MODE: z.coerce.boolean().default(false),
  JWT_SECRET: z.string().min(16).default('transferly-development-secret'),
  JWT_EXPIRES_IN_SECONDS: z.coerce.number().int().positive().default(3600),
  JWT_CLOCK_SKEW_SECONDS: z.coerce.number().int().min(0).max(300).default(30),
  AUTH_SESSION_TTL_SECONDS: z.coerce.number().int().min(300).max(2592000).default(604800),
  AUTH_COOKIE_NAME: z.string().min(1).default('transferly_token'),
  PAYPAL_CLIENT_ID: z.string().min(1),
  PAYPAL_CLIENT_SECRET: z.string().min(1),
  PAYPAL_ENVIRONMENT: z.enum(['sandbox', 'production']).default('sandbox'),
  PAYPAL_WEBHOOK_ID: z.string().min(1),
  STRIPE_SECRET_KEY: z.string().default(''),
  STRIPE_WEBHOOK_SECRET: z.string().default(''),
  STRIPE_CONNECT_CLIENT_ID: z.string().default(''),
  STRIPE_CONNECTED_ACCOUNT_ID: z.string().default(''),
  STRIPE_PAYOUTS_ENABLED: z.coerce.boolean().default(false),
  STRIPE_PAYOUT_MODE: z.enum(['transfer_to_connected_account']).default('transfer_to_connected_account'),
  STRIPE_API_VERSION: z.string().default('2026-02-25.clover'),
  STRIPE_API_BASE_URL: z.string().url().default('https://api.stripe.com'),
  WISE_API_TOKEN: z.string().default(''),
  WISE_PROFILE_ID: z.string().default(''),
  WISE_WEBHOOK_PUBLIC_KEY: z.string().default(''),
  PAYSTACK_SECRET_KEY: z.string().default(''),
  PAYSTACK_WEBHOOK_SECRET: z.string().default(''),
  FLUTTERWAVE_SECRET_KEY: z.string().default(''),
  FLUTTERWAVE_WEBHOOK_SECRET: z.string().default(''),
  CRYPTO_COMMERCE_API_KEY: z.string().default(''),
  CRYPTO_COMMERCE_WEBHOOK_SECRET: z.string().default(''),
  CRYPTO_COMMERCE_API_BASE_URL: z.string().url().default('https://api.commerce.coinbase.com'),
  BINANCE_API_KEY: z.string().default(''),
  BINANCE_API_SECRET: z.string().default(''),
  BINANCE_API_BASE_URL: z.string().url().default('https://api.binance.com'),
  CASH_APP_API_KEY: z.string().default(''),
  CASH_APP_ENVIRONMENT: z.enum(['sandbox', 'production']).default('sandbox'),
  EMAIL_DELIVERY_WEBHOOK_URL: z.string().url().optional(),
  TELEGRAM_BOT_TOKEN: z.string().default(''),
  TELEGRAM_WEBHOOK_SECRET: z.string().default(''),
  TELEGRAM_API_BASE: z.string().url().default('https://api.telegram.org'),
  TELEGRAM_MINI_APP_URL: z.string().url().optional(),
  MINI_APP_URL: z.string().url().optional(),
  TELEGRAM_MINI_APP_AUTH_EXPIRES_IN_SECONDS: z.coerce.number().int().positive().default(3600),
  MAX_SINGLE_PAYOUT: z.coerce.number().positive().default(1000),
  DAILY_PAYOUT_LIMIT: z.coerce.number().positive().default(5000),
  MAX_PAYOUTS_PER_HOUR: z.coerce.number().int().positive().default(5),
  HIGH_RISK_COUNTRIES: z.string().default(''),
  HIGH_RISK_CURRENCIES: z.string().default(''),
  SUSPICIOUS_INVOICE_KEYWORDS: z.string().default('crypto,investment,loan,casino,gift card'),
  API_RATE_LIMIT_MAX: z.coerce.number().int().positive().default(120),
  API_RATE_LIMIT_WINDOW_MS: z.coerce.number().int().positive().default(60000),
  API_REQUEST_TIMEOUT_MS: z.coerce.number().int().min(1000).max(300000).default(30000),
  AUTH_RATE_LIMIT_MAX: z.coerce.number().int().positive().default(20),
  AUTH_RATE_LIMIT_WINDOW_MS: z.coerce.number().int().positive().default(60000),
  CORS_ALLOWED_ORIGINS: z.string().default(''),
  JOB_WAIT_MS: z.coerce.number().int().positive().optional(),
  WEBHOOK_QUEUE_WAIT_MS: z.coerce.number().int().positive().optional(),
  GENERATED_ASSET_CLEANUP_INTERVAL_MS: z.coerce.number().int().min(60000).max(2592000000).default(21600000),
  GENERATED_ASSET_CLEANUP_BATCH_SIZE: z.coerce.number().int().min(1).max(500).default(100),
  GENERATED_ASSET_ORPHAN_DELETE_ENABLED: z.coerce.boolean().default(false),
  GENERATED_ASSET_DOWNLOAD_TTL_SECONDS: z.coerce.number().int().min(30).max(900).default(300),
  ORDER_PROCESSING_LOCK_TTL_MS: z.coerce.number().int().min(5000).max(86400000).default(900000),
  POINT_RESERVATION_TTL_MS: z.coerce.number().int().min(60000).max(2592000000).default(86400000),
  POINT_RESERVATION_EXPIRY_INTERVAL_MS: z.coerce.number().int().min(60000).max(86400000).default(300000),
  POINT_RESERVATION_EXPIRY_BATCH_SIZE: z.coerce.number().int().min(1).max(500).default(100),
  POINTS_TO_NAIRA_RATE: z.coerce.number().int().positive().default(1),
  DEFAULT_SERVICE_POINT_CHARGE: z.coerce.number().int().positive().default(250),
  POINTS_FUNDING_DESTINATION_ACTIVE: z.coerce.boolean().default(true),
  POINTS_FUNDING_BANK_PROVIDER: z.string().default('Configured Bank'),
  POINTS_FUNDING_ACCOUNT_NAME: z.string().default('TRANSFERLY CONFIG REQUIRED'),
  POINTS_FUNDING_ACCOUNT_NUMBER: z.string().default('0000000000'),
  POINTS_FUNDING_PAYMENT_NOTE: z.string().default('Include your Transferly payment reference in the bank transfer narration.'),
  POINTS_FUNDING_INSTRUCTIONS: z.string().default('Transfer exactly the amount shown. 1 Transferly Point equals ₦1.'),
  PAYMENT_VERIFICATION_ENABLED: z.coerce.boolean().default(false),
  PAYMENT_AUTO_APPROVAL_ENABLED: z.coerce.boolean().default(false),
  PAYMENT_AUTO_APPROVAL_MAX_AMOUNT_MINOR: z.coerce.number().int().min(0).default(0),
  PAYMENT_WEBHOOK_TIMESTAMP_TOLERANCE_SECONDS: z.coerce.number().int().positive().default(300),
  RISK_ENGINE_ENABLED: z.coerce.boolean().default(true),
  RISK_REVIEW_ENABLED: z.coerce.boolean().default(true),
  AUTO_RESTRICTION_ENABLED: z.coerce.boolean().default(false),
  HIGH_RISK_AUTO_REVIEW_ENABLED: z.coerce.boolean().default(true),
  MAX_FUNDING_ATTEMPTS_PER_HOUR: z.coerce.number().int().positive().default(5),
  MAX_DAILY_FUNDING_AMOUNT: z.coerce.number().int().positive().default(25000000),
  LARGE_FUNDING_THRESHOLD: z.coerce.number().int().positive().default(10000000),
  MAX_SERVICE_ACTIONS_PER_MINUTE: z.coerce.number().int().positive().default(20),
  MAX_SERVICE_ACTIONS_PER_HOUR: z.coerce.number().int().positive().default(200),
  MAX_REFUND_REQUESTS_PER_DAY: z.coerce.number().int().positive().default(5),
  MAX_FAILED_PAYMENT_ATTEMPTS: z.coerce.number().int().positive().default(5),
  RAPID_POINT_CONSUMPTION_THRESHOLD: z.coerce.number().int().positive().default(25000),
  LARGE_ADMIN_ADJUSTMENT_THRESHOLD: z.coerce.number().int().positive().default(10000),
  RISK_SIGNAL_RETENTION_DAYS: z.coerce.number().int().positive().default(365),
  RISK_CASE_RETENTION_DAYS: z.coerce.number().int().positive().default(1095),
  OPAY_WEBHOOK_SECRET: z.string().default(''),
  ADMIN_API_TOKEN: z.string().default(''),
  BOT_API_HMAC_SECRET: z.string().default(''),
  API_HMAC_SECRET: z.string().default(''),
  BOT_API_HMAC_REQUIRED: z.coerce.boolean().default(false),
  BOT_API_HMAC_MAX_AGE_MS: z.coerce.number().int().positive().default(300000),
  BOT_API_HMAC_REPLAY_PROTECTION: z.coerce.boolean().default(true),
  BOT_API_HMAC_REPLAY_STORE: z.enum(['memory', 'redis']).optional(),
  BOT_API_HMAC_REPLAY_KEY_PREFIX: z.string().min(1).default('transferly:bot-api-replay'),
  ADMIN_API_ACTOR_ID: z.string().default(''),
  USER_API_TOKENS: z.string().default(''),
  SEED_USER_ID: z.string().min(1).optional(),
  SEED_USER_EMAIL: z.string().email().optional(),
  SEED_USER_NAME: z.string().min(1).optional(),
  SEED_USER_COUNTRY: z.string().length(2).optional(),
  SEED_WALLET_CURRENCY: z.string().length(3).optional(),
  SEED_PENDING_BALANCE: z.coerce.number().int().min(0).optional(),
  SEED_AVAILABLE_BALANCE: z.coerce.number().int().min(0).optional(),
  SEED_FROZEN_BALANCE: z.coerce.number().int().min(0).optional(),
  SEED_PAID_OUT_BALANCE: z.coerce.number().int().min(0).optional(),
  SEED_ADMIN_ACTOR_ID: z.string().min(1).optional(),
  TRANSFERLY_OWNER_TELEGRAM_USER_IDS: z.string().default(''),
  TRANSFERLY_ADMIN_TELEGRAM_USER_IDS: z.string().default(''),
  SERVICE_FEATURE_FLAGS: z.string().default(''),
  PAYMENT_PROVIDER_FEATURE_FLAGS: z.string().default(''),
  PAYPAL_ONLY_PRODUCTION_MVP: z.enum(['true', 'false']).transform((value) => value === 'true').default('true')
});

const parsed = envSchema.parse(process.env);
const derived = deriveEnvironmentConfig(parsed);
validateProductionConfig(parsed, derived);
const sqliteDatabasePath = derived.SQLITE_DATABASE_PATH;
mkdirSync(path.dirname(sqliteDatabasePath), { recursive: true });

module.exports = {
  ...parsed,
  ...derived
};
